import { chromium } from 'playwright';
import http from 'node:http'; import { readFileSync, existsSync } from 'node:fs'; import { extname, join } from 'node:path';
const root = new URL('../', import.meta.url).pathname;
const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.json': 'application/json' };
const srv = http.createServer((req, res) => { const f = join(root, decodeURIComponent(req.url.split('?')[0]).replace(/^\/$/, '/index.html')); if (!f.startsWith(root) || !existsSync(f)){ res.writeHead(404); res.end(); return; } res.writeHead(200, { 'content-type': types[extname(f)] || 'text/plain' }); res.end(readFileSync(f)); });
await new Promise(r => srv.listen(0, '127.0.0.1', r));
const url = `http://127.0.0.1:${srv.address().port}/index.html`;
const out = '/tmp/claude-0/-home-user-Little-Strategy-Game/f49a44a8-52a9-51b6-901c-d71817445272/scratchpad/shots/';
const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1280, height: 720 }, locale: 'de-DE' });
const p = await ctx.newPage(); const errs = [];
p.on('console', m => { if (m.type() === 'error' && !/ERR_CERT|fonts\.g/.test(m.text())) errs.push(m.text()); if (m.type() === 'warning') errs.push(m.text()); });
p.on('pageerror', e => errs.push(e.message));
await p.goto(url); await p.waitForTimeout(500);
const st = () => p.evaluate(() => { const v = __kf.Tutorial.view(); return { t: +__kf.G.S.t.toFixed(1), phase: v.phase, step: v.step && v.step.id, idx: v.index, narr: document.querySelector('#tutBubbleNarr').textContent, task: document.querySelector('#tutBubbleTask').textContent, vis: !document.querySelector('#tutBubble').hidden, marked: [...document.querySelectorAll('.tut-target')].map(e => e.id || e.dataset.tooltip), diff: __kf.G.S.diff, lang: __kf.lang, status: __kf.G.S.status }; });
console.log('dialog', JSON.stringify(await p.evaluate(() => ({ modal: !document.querySelector('#modal').hidden, pressedDiff: [...document.querySelectorAll('.diff')].map(b => b.getAttribute('aria-pressed') + ':' + b.textContent.slice(0, 40)), tut: document.querySelector('[data-tooltip="tutorialSwitch"]').getAttribute('aria-pressed'), lang: document.documentElement.lang, status: __kf.G.S.status }))));
await p.screenshot({ path: out + 't2-0-dialog.png' });
await p.click('.card .btn-primary'); await p.waitForTimeout(700);
console.log('greet1', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-1-greet1.png' });
await p.click('#tutBubble'); await p.waitForTimeout(400);
console.log('greet2', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-2-greet2.png' });
await p.waitForTimeout(4300);
console.log('step1 (auto)', JSON.stringify(await st()));
await p.waitForTimeout(2600);
console.log('step1 text', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-3-step1.png' });
for (let i = 0; i < 10; i++){ await p.click('#clickBtn'); await p.waitForTimeout(90); }
await p.waitForTimeout(2800); console.log('bauen', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-4-bauen.png' });
const pr = await p.evaluate(() => { const r = __kf.plotRects[0]; return __kf.worldToScreen(r.x + r.w / 2, r.y + r.h / 2); });
await p.mouse.click(pr.x, pr.y); await p.waitForTimeout(250); await p.click('#ctxBuild .pick'); await p.waitForTimeout(250);
await p.click('#tab-army'); await p.waitForTimeout(250); console.log('armee', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-5-armee.png' });
for (let i = 0; i < 60 && !(await p.evaluate(() => __kf.Tutorial.isDone('rekrutieren'))); i++){ await p.keyboard.press('1'); await p.click('#clickBtn'); await p.waitForTimeout(150); }
await p.waitForTimeout(300); console.log('welle', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-6-welle.png' });
await p.waitForFunction(() => __kf.Tutorial.isDone('ausruecken'), null, { timeout: 40000 });
await p.waitForFunction(() => __kf.Tutorial.view().step && __kf.Tutorial.view().step.id === 'karte' && !document.querySelector('#tutBubble').hidden, null, { timeout: 120000 });
await p.waitForTimeout(600); console.log('karte', JSON.stringify(await st()), JSON.stringify(await p.evaluate(() => ({ xp: __kf.G.S.xpTotal, need: __kf.G.xpNeed(1), pending: !!__kf.G.S.pendingDraft, tab: __kf.tab, bounty: __kf.G.S.stats.xpBounty })))); await p.screenshot({ path: out + 't2-7-karte.png' });
await p.waitForTimeout(500); await p.click('#draftOffer .card-pick'); await p.waitForTimeout(500);
console.log('bye1', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-8-bye1.png' });
await p.click('#tutBubble'); await p.waitForTimeout(300); console.log('bye2', JSON.stringify(await st()));
await p.click('#tutBubble'); await p.waitForTimeout(900); console.log('leaving', JSON.stringify(await st())); await p.screenshot({ path: out + 't2-9-leaving.png' });
await p.waitForTimeout(1500); console.log('ende', JSON.stringify(await st()), JSON.stringify(await p.evaluate(() => __kf.Tutorial.data())));
console.log('errs', errs);
await b.close(); srv.close();
